### ISSUE TITLE
Máscara de ISBN.

### ISSUE THREAD

**Issue by alephmelo** [dhelbegor/easy-mask#2]
Talvez poderia ter uma máscara de ISBN (International Standard Book Number) 

``` python
{% for data in personal %}
  <tr>
    <td>{{ data.isbn | isbn }}</td>
  </tr>
{% endfor %}
```

``` html
<td>978-85-333-0227-3</td>
```

Não sei até que ponto é válido ter a separação, mas pode ser que ajude pessoas da área a identificar alguns termos de atribuição logo de cara.

**Comment by dhelbegor** [comment]
Esta foi uma ótima sugestão Aleph, obrigado.
